### ISSUE TITLE
nifty installs but cannot be imported on travis

### ISSUE THREAD

**Issue by clbarnes** [constantinpape/elf#11]

**Comment by constantinpape** [comment]
Yes, unfortunately I can't see the import error, so it's hard to tell what exactly is going wrong.
(I have tried the package locally and it works).
I am trying to bring nifty on conda-forge, but it's slow going. I hope that I will have some 
time to look into this soon.
https://github.com/conda-forge/staged-recipes/pull/7763

**Comment by constantinpape** [comment]
The issue was that the travis build used python 3.6, for which the available nifty version was broken.
Fixed by moving travis to python 3.7.
