### ISSUE TITLE
Installation/build issue

### ISSUE THREAD

**Issue by Nickkzz97** [constantinpape/elf#25]
While using conda install directly using 

> conda install -c conda-forge -c cpape nifty

 I'm getting this error,

> ImportError                               Traceback (most recent call last)
> <ipython-input-73-8598a969557d> in <module>()
> ----> 1 import nifty
> 
> 1 frames
> /usr/local/lib/python3.7/site-packages/nifty/graph/__init__.py in <module>()
>       1 # sphinx_gallery_thumbnail_number = 4
>       2 from __future__ import absolute_import
> ----> 3 from nifty.graph import graph as __graph
>       4 from ._graph import *
>       5 
> 
> ImportError: cannot import name 'graph'
> 
> ---------------------------------------------------------------------------
> NOTE: If your import is failing due to a missing package, you can
> manually install dependencies using either !pip or !apt.

and with source getting a part of error as,

> In file included from /usr/local/envs/nifty-dev/include/python3.7m/pybind11/cast.h:15:0,
>                  from /usr/local/envs/nifty-dev/include/python3.7m/pybind11/attr.h:13,
>                  from /usr/local/envs/nifty-dev/include/python3.7m/pybind11/pybind11.h:43,
>                  from /gdrive/My Drive/Biomedical Image Processing ED6001/Biomedical Project/elf/nifty/src/python/lib/graph/undirected_list_graph.cxx:1:
> /usr/local/envs/nifty-dev/include/python3.7m/pybind11/detail/descr.h:34:61: note: candidate: template<long unsigned int OtherSize1, long unsigned int OtherSize2> constexpr pybind11::detail::descr<(Size1 + OtherSize1), (Size2 + OtherSize2)> pybind11::detail::descr<Size1, Size2>::operator+(const pybind11::detail::descr<OtherSize1, OtherSize2>&) const [with long unsigned int OtherSize1 = OtherSize1; long unsigned int OtherSize2 = OtherSize2; long unsigned int Size1 = 9; long unsigned int Size2 = 1]
>      constexpr descr<Size1 + OtherSize1, Size2 + OtherSize2> operator+(const descr<OtherSize1, OtherSize2> &other) const {
>                                                              ^~~~~~~~
> /usr/local/envs/nifty-dev/include/python3.7m/pybind11/detail/descr.h:34:61: note:   template argument deduction/substitution failed:
> In file included from /gdrive/My Drive/Biomedical Image Processing ED6001/Biomedical Project/elf/nifty/src/python/lib/graph/undirected_list_graph.cxx:1:0:
> /usr/local/envs/nifty-dev/include/python3.7m/pybind11/pybind11.h:167:79: note:   mismatched types ‘const pybind11::detail::descr<OtherSize1, OtherSize2>’ and ‘void’
>          PYBIND11_DESCR signature = _("(") + cast_in::arg_names() + _(") -> ") + cast_out::name();
>                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
> src/python/lib/graph/CMakeFiles/_graph.dir/build.make:75: recipe for target 'src/python/lib/graph/CMakeFiles/_graph.dir/undirected_list_graph.cxx.o' failed
> make[2]: *** [src/python/lib/graph/CMakeFiles/_graph.dir/undirected_list_graph.cxx.o] Error 1
> CMakeFiles/Makefile2:1370: recipe for target 'src/python/lib/graph/CMakeFiles/_graph.dir/all' failed
> make[1]: *** [src/python/lib/graph/CMakeFiles/_graph.dir/all] Error 2
> Makefile:140: recipe for target 'all' failed
> make: *** [all] Error 2

I'm trying it in colab using anaconda of  conda version : 4.9.2, linux64 and python version of 3.7.
Where am I getting wrong??

**Comment by constantinpape** [comment]
This issue should be fixed by using nifty from conda-forge.
