### ISSUE TITLE
bug in lifted_problem_from_segmentation

### ISSUE THREAD

**Issue by lorenzocerrone** [constantinpape/elf#33]
Hi Constantin, 

I was trying to solve the lifted problem from segmentation and I think I might have found a bug in `elf.segmentation.features.lifted_problem_from_segmentation`. 

If I run it the lifted costs have dimensions `#nodes x 2` but I think they should be just `#nodes`. 
Is it be enough to change this line:
https://github.com/constantinpape/elf/blob/208c6142b4f2a292c39827c255f5d985f33eecfa/elf/segmentation/features.py#L499
to something like `lifted_costs = np.zeros(n_nodes, dtype='float32')`?
if so I could open a PR

cheers, 

Lorenzo

**Comment by constantinpape** [comment]
Hi Lorenzo,

there was ineed a bug, but the shape needs to be `#lifted edges` (it was `#lifted edges x 2`). I have fixed this now, could you pull the latest changes and see if it works for you now?

**Comment by lorenzocerrone** [comment]
Looks good to me! Thanks a lot!
