### ISSUE TITLE
  File "/opt/conda/lib/python3.8/site-packages/elf-0.3.0-py3.8.egg/elf/segmentation/__init__.py", line 1, in <module>     from .clustering import (agglomerative_clustering,   File "/opt/conda/lib/python3.8/site-packages/elf-0.3.0-py3.8.egg/elf/segmentation/clustering.py", line 2, in <module>     import nifty.graph.agglo as nagglo ModuleNotFoundError: No module named 'nifty.graph'

### ISSUE THREAD

**Issue by coder-people** [constantinpape/elf#43]
File "/opt/conda/lib/python3.8/site-packages/elf-0.3.0-py3.8.egg/elf/segmentation/__init__.py", line 1, in <module>
    from .clustering import (agglomerative_clustering,
  File "/opt/conda/lib/python3.8/site-packages/elf-0.3.0-py3.8.egg/elf/segmentation/clustering.py", line 2, in <module>
    import nifty.graph.agglo as nagglo
ModuleNotFoundError: No module named 'nifty.graph'

**Comment by constantinpape** [comment]
I would need more information than this:
- what code are you trying to run?
- how is elf installed?
- what environment is this? (which os, which conda version, which python version)

**Comment by constantinpape** [comment]
Closed due to inactivity
