### ISSUE TITLE
Connecting disjoint segments of the same instance

### ISSUE THREAD

**Issue by aswahd** [constantinpape/elf#62]
How to use segmentation/mutex_watershed to join disconnected segments of the same object. A short explanatory example can be found at [Mutex-Watershed-Instance-segmentation](https://github.com/aswahd/Mutex-Watershed-Instance-segmentation).

Link to segmentation/mutex_watershed function: 

https://github.com/constantinpape/elf/blob/51f5aef076d39ef4416dbd01915bc3d7c1623005/elf/segmentation/mutex_watershed.py#L14-L42

**Comment by aswahd** [comment]
For example, apply mutex watershed gives the following instance segmentation. Then, I want to join the separate segments.
![zoomed-in](https://user-images.githubusercontent.com/53992505/177897960-9315c1b1-510d-4def-ba9a-b237ed585672.png)

**Comment by aswahd** [comment]
Hello @constantinpape,
Can you please share the link to the code?

Thank you.

**Comment by constantinpape** [comment]
Hi @aswahd,
there is no ready-made functionality / example for this scenario yet, but `nifty` (the c++ library that is used for many of the `elf` features under the hood) has the functionality needed to implement it.
I created a minimal example with random data here: https://gist.github.com/constantinpape/66b04be4c6fca146e7d2a1c074081035 
But you will need to adapt it / tune the parameters to make it work for your problem.

**Comment by aswahd** [comment]
@constantinpape 
Thank your very much.
I really appreciate it.
