### ISSUE TITLE
missing functionality

### ISSUE THREAD

**Issue by martinschorb** [constantinpape/elf#80]
Hi @constantinpape ,

when trying to import mobie, we run into

```
  File "/.../cluster_tools/watershed/watershed.py", line 9, in <module>
    from elf.util import set_numpy_threads
ImportError: cannot import name 'set_numpy_threads' from 'elf.util'
```

where is that function gone?

**Comment by constantinpape** [comment]
Hi @martinschorb ,
I recently removed this functionality, since there are much better options for this now with `threadpoolctl`. I didn't realize that the downstream functionality in `cluster_tools` is also affected. I will update it in the evening and make a new release.

Thanks for noticing!

**Comment by constantinpape** [comment]
This will fix it: https://github.com/constantinpape/cluster_tools/pull/41

**Comment by constantinpape** [comment]
New release is there: https://github.com/constantinpape/cluster_tools/releases/tag/0.4.6
Should be on conda-forge in the next few days and then fix the issue also when setting up everything via conda.

**Comment by constantinpape** [comment]
The conda forge bot was fast, it's already there.
